repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: trailing-whitespace
    exclude: README.md
  - id: check-yaml
  - id: check-json

- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    name: Blacken

- repo: local
  hooks:
  - id: codecov-validator
    name: Validate .codecov.yml
    description: Validate .codecov.yml using codecov's online validation tool.
    entry: ./.ci/codecov-validator.sh
    files: >
      (?x)^(
        .codecov.yml
      )$
    language: system

  - id: optimade-version
    name: Update OPTiMaDe shield
    description: If needed, the json for the OPTiMaDe shield will be updated with new config version
    entry: python ./.ci/optimade_version_update.py
    files: >
      (?x)^(
        .ci/optimade-version.json|
        aiida_optimade/config.json
      )$
    language: system
