version: '2'

services:
  aiida-optimade:
    restart: always
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        # replace default value by v1.0.1 once released
        AIIDA_VERSION: 196a074c45774de2c4bde6dbebb8b952b695eb4a
    environment:
      AIIDA_PATH: /app
      AIIDA_PROFILE: quicksetup
    volumes:
     - '/Users/leopold/Personal/Postdoc-MARVEL/aiida_folders/aiida_rmq/.aiida/repository-quicksetup:/app/.aiida/repository-quicksetup'
     - '/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida-optimade/profiles:/profiles'
    ports:
      - '3253:80'
